# On conserve les deux providers
providers = ["node", "php"]

[variables]
PHP_EXTENSIONS = ""
# On force la version 20 pour le provider Node natif
NIXPACKS_NODE_VERSION = "20"

[phases.setup]
# IMPORTANT : On retire "nodejs_20" d'ici pour éviter le doublon
nixPkgs = ["php", "nginx", "phpPackages.composer"]