# On indique explicitement les deux frameworks/langages du projet
providers = ["node", "php"]

[variables]
# Force la version de Node sur le provider natif
NIXPACKS_NODE_VERSION = "20"

# Permet d'éviter les crashs de détection automatique d'extensions PHP complexes
PHP_EXTENSIONS = ""