# Déclare la liste des providers à utiliser (Séquence TOML)
providers = ["node", "php"]

[variables]
# Évite le plantage sur la détection automatique des extensions complexes
PHP_EXTENSIONS = ""
# C'est ici qu'on force proprement la version globale de Node pour Nixpacks
NIXPACKS_NODE_VERSION = "20"

[phases.setup]
# Vos paquets requis pour l'environnement
nixPkgs = ["php", "nodejs_20", "nginx", "phpPackages.composer"]